### ISSUE TITLE
Module '"./qr-generator.common"' has no exported member 'Common'.

### ISSUE THREAD

**Issue by Vatrax** [erodriguezh/nativescript-qr-generator#1]
Hi, 
I am new to angular and nativescript and I wanted to use your plugin. Unfortunately after installation I cannot run your Usage guide. I receive:
```
ERROR in node_modules/nativescript-qr-generator/index.d.ts:1:10 - error TS2305: Module '"./qr-generator.common"' has no exported member 'Common'.

 import { Common, QROptions } from './qr-generator.common';
           ~~~~~~
node_modules/nativescript-qr-generator/index.d.ts:6:50 - error TS2304: Cannot find name 'UIImage'.

   generate (value: string, options?: QROptions): UIImage;
                                                   ~~~~~~~
```
It looks like there is issue with this plugin, but on the other hand I am running your demo without any problem. Can You help me? :)

**Comment by erodriguezh** [comment]
Hi @Vatrax 

I created an Angular project for you to compare with your code. The repo is [here](https://github.com/erodriguezh/issue-1). I hope it helps.

**Comment by Vatrax** [comment]
Hello, 
finally I have found where is the problem. The difference between my project and yours was in tns.config. Adding skipLibCheck compiler option fixed the issue. 
Thank You.

**Comment by erodriguezh** [comment]
Thats good news, i will close the ticket then
