### ISSUE TITLE
hebrew letters are shown as ????

### ISSUE THREAD

**Issue by arLevi** [erodriguezh/nativescript-qr-generator#24]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Cannot generate a QR with hebrew letters, they appear as "???" once i scan it.

### Which platform(s) does your issue occur on?
- Android
- 8.1.0
- device: real, Pocophone F1

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2
- Cross-platform modules: don't have tns-core-modules
- Runtime(s): 8.0.0
- Plugin(s): "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@nativescript/angular": "~12.0.0",
    "@nativescript/core": "~8.0.0",
    "@nativescript/theme": "~3.0.1",
    "nativescript-qr-generator": "^2.0.0",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~12.0.0",
    "@nativescript/android": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~12.0.0",
    "typescript": "~4.2.0"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
I just created a 'hello world' app by running `tns create myapp` ( Chose Angular & Hello world in the CLI )
Then i just created inside `item-detail.component.html`
```
<ActionBar title="Details"></ActionBar>

<FlexboxLayout flexDirection="column">
  <FlexboxLayout class="m-15">
    <Label class="h2" [text]="item.id + '. '"></Label>
    <Label class="h2" [text]="item.name"></Label>
    <Label class="h2" text="בדיקת עברית"></Label>         <= Another test i've done to make sure hebrew is working ok
  </FlexboxLayout>
 
  <Image src="" (loaded)="onImageLoaded($event)"></Image>
</FlexboxLayout>
```

and `item-detail.component.ts` the examples you have in GitHub

The QR it self works - just not in other langauages
So instead of: 
`const result = new QrGenerator().generate('Hello World');`

I added another word in Hebrew
`const result = new QrGenerator().generate('Hello World בדיקה');`

### Is there any code involved? 
Not applicable

When you scan it with a QR scanner - you'll see that it's resulting with "Hello World ????"
<img src="https://user-images.githubusercontent.com/1129836/144414286-6046de53-5734-41d8-ba73-7c3ade9fd5eb.jpeg" width="200" height="auto">

**Comment by erodriguezh** [comment]
Hi @arLevi,
I moved the code to a [new repo](https://github.com/erodriguezh/nsplugins). 
Regarding to the issue, feel free to open a PR. 
Thanks
